FROM mcr.microsoft.com/dotnet/aspnet:3.1-buster-slim AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:3.1-buster AS build
WORKDIR /src

COPY ["DatabaseMigrator/DatabaseMigrator.csproj", "DatabaseMigrator.csproj"]

RUN dotnet restore "DatabaseMigrator.csproj"

COPY . .

WORKDIR "/src"
RUN dotnet build "DatabaseMigrator.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "DatabaseMigrator.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

COPY CompanyName.MyMeetings.Database/Scripts/Migrations /migrations/

ENTRYPOINT dotnet DatabaseMigrator.dll "Server=${MSSQL_SERVER},${MSSQL_PORT};Database=${MSSQL_DATABASE};User=${MSSQL_USER};Password=${MSSQL_PASSWORD}" "/migrations" 120